name: image_generation
description: Generate Image Form Flutter Widget
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  external_path: ^1.0.3
  flutter:
    sdk: flutter
  image_downloader_web: ^2.0.4
  open_filex: ^4.3.4
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
